# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController::number

blog_list:
    path: /blog
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\BlogController::list

about-me:
    path: /about-me
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\LearningController::aboutMe